[project]
name = "mlops-labs-26-27"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Jan Wójcik", email = "jan.wojcik077@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.11.2",
    "numpy>=2.5.3",
    "pre-commit>=4.6.2",
]

[project.scripts]
mlops-labs-26-27 = "mlops_labs_26_27:main"

[build-system]
requires = ["uv_build>=0.12.23,<0.13.0"]
build-backend = "uv_build"
